# conda env create -f environment.yml
name: aiera-gpt
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - pydantic
  - pandas
  - jupyterlab
  - streamlit
  - versioneer
  - pydantic-settings
  - mysqlclient
  - tiktoken
  - pymysql
  - sqlalchemy
  - pysqlite3
  - pip:
    - streamlit-chat
    - openai