# conda env create -f environment.yml
name: aiera-assistant
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - pydantic
  - pandas
  - jupyterlab
  - streamlit
  - versioneer
  - pydantic-settings
  - tiktoken
  - pip:
    - streamlit-chat
    - openai